routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Building.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use common\Helper;

class Building extends Model
{
    protected $table = 'building';
    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->slug = Helper::convert_string($model->name);
        });
    }

    public function rooms() {
        return $this->hasMany('App\Models\Rooms', 'building_id');
    }

    public function getTotalBoxAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->boxs()->count();
        }
        
        return $total;
    }

    public function getTotalBoxSoldoutAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->boxs()->where('status', 1)->count();
        }
        
        return $total;
    }

    public function getTotalBoxSingleAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->count_box_single;
        }
        
        return $total;
    }

    public function getTotalBoxSingleSoldoutAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->count_box_single_soldout;
        }
        
        return $total;
    }

    public function getTotalBoxDubbleAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->count_box_dubble;
        }
        
        return $total;
    }

    public function getTotalBoxDubbleSoldoutAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->count_box_dubble_soldout;
        }
        
        return $total;
    }

    public function getTotalPriceSingleAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            
            $total += $room->count_money_single;
            
        }
        return $total;
    }

    public function getTotalPriceDubbleAttribute() {
        $rooms = $this->rooms()->get();
        $total = 0;
        if (count($rooms) == 0) {
            return 0;
        }
        foreach($rooms as $room) {
            $total += $room->count_money_dubble;
        }
        
        return $total;
    }

    public function getTotalPriceBuildingAttribute() {
        return $this->total_price_dubble + $this->total_price_single;
    }
}

app/Models/Rooms.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use common\Helper;

class Rooms extends Model
{
    protected $table = 'rooms';

    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->slug = Helper::convert_string($model->name);
        });
    }


    public function building() {
        return $this->belongsTo('App\Models\Building', 'building_id');
    }

    public function boxs() {
        return $this->hasMany('App\Models\Boxs', 'room_id');
    }

    public function getCountBoxSingleAttribute() {
        return $this->boxs()->where("box_type_id", 1)->count();
    }

    public function getCountBoxSingleSoldoutAttribute() {
        return $this->boxs()->where("box_type_id", 1)->where("status", 1)->count();
    }

    public function getCountMoneySingleAttribute() {
        $boxs = $this->boxs()->where('box_type_id', 1)->get();
        $total = 0;
        if (count($boxs) == 0) {
            return 0;
        }
        foreach($boxs as $box) {
            $total += $box->humanDeath()->sum('money_info');
        }
        
        return $total;
    }

    public function getCountBoxDubbleAttribute() {
        return $this->boxs()->where("box_type_id", 2)->count();
    }

    public function getCountBoxDubbleSoldoutAttribute() {
        return $this->boxs()->where("box_type_id", 2)->where("status", 1)->count();
    }

    public function getCountMoneyDubbleAttribute() {
        $boxs = $this->boxs()->where('box_type_id', 2)->get();
        $total = 0;
        if (count($boxs) == 0) {
            return 0;
        }
        foreach($boxs as $box) {
            $total += $box->humanDeath()->sum('money_info');
        }
        
        return $total;
    }
}

resources/views/admin/statistic/index.blade.php
<style type="text/css">
  table.table-bordered{
    border:1px solid #001f3f!important;
    margin-top:20px;
  }
table.table-bordered > thead > tr > th{
    border:1px solid #001f3f!important;
}
table.table-bordered > tbody > tr > td{
    border:1px solid #001f3f!important;
}
table.table-bordered > tfoot > tr > td{
    border:1px solid #001f3f!important;
}

#finance-loader {
  display: none;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 20px;
  height: 20px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
  position: absolute;
  top: 50%;
  left: 50%;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
#statisticFinance {
  position: relative;
}

</style>
<div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <label>Bảng theo dõi toà nhà</label>
      <select id="buildingStatistic" name="state">
        @foreach($data['buildings'] as $key => $building)
          @if($key == $data['building']->id)
            <option value="{{$key}}" selected>{{$building}}</option>
          @else
            <option value="{{$key}}">{{$building}}</option>
          @endif
        @endforeach
      </select>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div id="statisticFinance">
        <div id="finance-loader"></div>
        @include('admin.statistic.partion', ["data" => $data])
      </div>
    </div>
  </div>
</div>

@include('admin.dashboard.chart', ["data" => $data])

resources/views/admin/statistic/partion.blade.php
<div id="tableStatisticFinance" >
  <table class="table table-responsive">
    <tbody>
      <tr>
        <td class="col">Tổng số ô: {{$data['building']->total_box}}</td>
        <td class="col">Tổng số ô đã đăng ký: {{$data['building']->total_box_soldout}}</td>
      </tr>
      <tr>
        <td class="col">Tổng số ô đơn: {{$data['building']->total_box_single}}</td>
        <td class="col">Tổng số ô đơn đã đăng ký: {{$data['building']->total_box_single_soldout}}</td>
      </tr>
      <tr>
        <td class="col">Tổng số ô đôi: {{$data['building']->total_box_dubble}}</td>
        <td class="col">Tổng số ô đôi đã đăng ký: {{$data['building']->total_box_dubble_soldout}}</td>
      </tr>
      <tr>
        <td colspan="2">Tổng số tiền của toà nhà: {{number_format($data['building']->total_price_building)}} VNĐ</td>
      </tr>
    </tbody>
  </table>
  <table class="table table-bordered vertical-align text-center table-responsive">
    <thead>
      <tr>
        <th rowspan="2">Phòng</th>
        <th colspan="4">Ô đơn</th>
        <th colspan="4">Ô đôi</th>
      </tr>
      <tr>
        <th>Tổng số ô</th>
        <th>Đã đăng ký</th>
        <th>Còn trống</th>
        <th>Tổng tiền (VNĐ)</th>
        <th>Tổng số ô</th>
        <th>Đã đăng ký</th>
        <th>Còn trống</th>
        <th>Tổng tiền (VNĐ)</th>
      </tr>
    </thead>
    @if(count($data['building']->rooms) > 0)
      <tbody>
        @foreach($data['building']->rooms as $room)
          <tr>
            <td>{{$room->name}}</td>
            <td>{{$room->count_box_single}}</td>
            <td>{{$room->count_box_single_soldout}}</td>
            <td>{{(int)$room->count_box_single - (int)$room->count_box_single_soldout}}</td>
            <td>{{number_format($room->count_money_single)}}</td>
            <td>{{$room->count_box_dubble}}</td>
            <td>{{$room->count_box_dubble_soldout}}</td>
            <td>{{(int)$room->count_box_dubble - (int)$room->count_box_dubble_soldout}}</td>
            <td>{{number_format($room->count_money_dubble)}}</td>
          </tr>
        @endforeach
      </tbody>
      <tfoot>
        <tr>
          <td>Tổng tiền (VNĐ)</td>
          <td colspan="4">{{number_format($data['building']->total_price_single)}}</td>
          <td colspan="4">{{number_format($data['building']->total_price_dubble)}}</td>
        </tr>
      </tfoot>
      @else
      <tbody>
        <tr><td colspan="9">Không có dữ liệu hiển thị.</td></tr>
      </tbody>  
    @endif
    
  </table>
</div>